### ISSUE TITLE
Some Chinese charaters can't be showed.

### ISSUE THREAD

**Issue by FormerNoob** [ONElua/TrophyManager#2]
I think the system' s font is not completed.

**Comment by FormerNoob** [comment]
Especially the simple chinese.

**Comment by ONElua** [comment]
https://github.com/theheroGAC/Autoplugin/blob/master/translations/font/font.pgf
ok
next version 
ssupport for fonts

**Comment by ONElua** [comment]
Please try v1.02 and put the font.pgf

**Comment by FormerNoob** [comment]
Oh yeah! It displays perfectly now! 
Thanks!
