### ISSUE TITLE
Trophy counter is broken or what ?

### ISSUE THREAD

**Issue by UnopposedForce91** [ONElua/TrophyManager#3]
The Counter of trophies on **the top right corner** is displaying the same number of trophies on the selected game, for example: ( X Game Has 1 Plat, 5 Gold, 10 Silvers and 9 bronze ) The counter is displaying this numbers , isnt it **useless ?** or is it an error from me ? if its not i would want it to displaying the total number of trophies i have **locally**.

**note** : i didnt sync the trophies with the server even once and i dont want to , so you can say all the trophies is stored **locally**

**system** : PS Vita 2000 3.65 Enso

**P.S :**  maybe you can add an option to show and edit the local or online trophies

**photo** :
![2019-05-07-174631](https://user-images.githubusercontent.com/50371589/57309394-ae491d80-70f0-11e9-8e0e-c3499bbf02be.jpg)

**Comment by ONElua** [comment]
press enter in each trophy
![image](https://user-images.githubusercontent.com/25811032/59150427-e6da6080-89e8-11e9-91f1-6c15d842cb75.png)

**Comment by PSVitaGamer** [comment]
@ONElua what do you mean with "enter" ?
i opened every single trophy in the trophy app + trophy manger and that didnt solve the problem
i notice another problem, when opening a sub-trophy list in trophy manger if i want to go back to the games list i cant cuz it will close
